import { GoogleGenAI, Type } from "@google/genai";
import { PassportAnalysis } from "../types";

// Helper to remove data URL prefix
const stripBase64Prefix = (dataUrl: string): string => {
  return dataUrl.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
};

const SYSTEM_INSTRUCTION = `
You are an expert biometric photography analyst for government passports. 
Your job is to strictly analyze passport photos for compliance with standard international (ICAO) regulations.
Regulations include:
1. Background: Must be plain white or off-white. No shadows.
2. Expression: Neutral expression, mouth closed, eyes open and looking at camera.
3. Lighting: Even lighting, no shadows on face or background.
4. Positioning: Face centered, full face visible, no head covering (unless religious), no glasses glare.
`;

export const analyzePassportPhoto = async (base64Image: string): Promise<PassportAnalysis> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  const cleanBase64 = stripBase64Prefix(base64Image);

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: "image/jpeg",
              data: cleanBase64
            }
          },
          {
            text: "Analyze this image for passport photo compliance. Return a JSON object detailing validity, a score out of 100, a list of specific issues found (if any), and suggestions for improvement."
          }
        ]
      },
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            isValid: { type: Type.BOOLEAN, description: "Whether the photo is likely to be accepted." },
            score: { type: Type.INTEGER, description: "A quality score from 0 to 100." },
            issues: { 
              type: Type.ARRAY, 
              items: { type: Type.STRING },
              description: "List of compliance violations."
            },
            suggestions: { 
              type: Type.ARRAY, 
              items: { type: Type.STRING },
              description: "Actionable advice to fix the photo."
            }
          },
          required: ["isValid", "score", "issues", "suggestions"]
        }
      }
    });

    const text = response.text;
    if (!text) {
      throw new Error("Empty response from AI");
    }

    return JSON.parse(text) as PassportAnalysis;

  } catch (error) {
    console.error("Gemini Analysis Error:", error);
    // Return a fallback error state so the UI doesn't crash
    return {
      isValid: false,
      score: 0,
      issues: ["AI Service Error: Could not analyze image."],
      suggestions: ["Please check your internet connection and try again."]
    };
  }
};

export const editPassportPhoto = async (
  base64Image: string, 
  prompt: string, 
  aspectRatio: '1:1' | '3:4' | '4:3' | '16:9' | '9:16' = '1:1'
): Promise<string> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) throw new Error("API Key not found");

  const ai = new GoogleGenAI({ apiKey });
  const cleanBase64 = stripBase64Prefix(base64Image);

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: "image/jpeg",
              data: cleanBase64
            }
          },
          {
            text: `Edit this passport photo. ${prompt} Keep the person's face, hair, and head dimensions exactly the same. The output must be realistic and high quality suitable for an ID document.`
          }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio 
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by the AI model");

  } catch (error) {
    console.error("Gemini Edit Error:", error);
    throw error;
  }
};